repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--target-version=py311, --line-length=95]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [markdown]
    -   id: end-of-file-fixer
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=95]
